### ISSUE TITLE
Not pushing from local server

### ISSUE THREAD

**Issue by ferreto1978** [ServerPress/wpsitesync#6]
Seems I'm not able to push anything from my local server.
It does however accept the "target settings" once WpSiteSyn is installed on target site as well, so it appears that the link is set.

Also (and probably related)
- The pages don't show the image tab in settings on the local server
They do show on the remote server (@one.com)
- The layout under the "Extensions" tab is not OK on the local server, but look fine on the remote.

![fail](https://user-images.githubusercontent.com/54818622/64131867-cfcec300-cdcb-11e9-8ef6-76f1781c55eb.png)

![fail2](https://user-images.githubusercontent.com/54818622/64131893-00166180-cdcc-11e9-85f9-dee787e13ced.png)

**Comment by davejesch** [comment]
Hi @ferreto1978 

I'm guessing that your local server is running Apache 2.4. In our next release, we've updated the .htaccess rules so that they are compatible with both Apache 2.2 and 2.4. To verify, if you would replace the wp-content/plugins/wpsitesynccontent/.htaccess file with the following:

` # Apache 2.2`
` <IfModule !mod_authz_core.c>`
`     Satisfy Any`
` ` 
`    <Files *.php>`
`        Require all denied`
`     </Files>`
` `
`    <Files ~*.txt>`
`        Order Deny,Allow`
`        deny from all`
`    </Files>`
` `
`    <files ".(xml|css|jpe?g|png|gif|js|ttf|wof|eof)$">`
`        Order Allow,Deny`
`        Allow from all`
`    </files>`
`</IfModule>`
` `
`# Apache 2.4`
`<IfModule mod_authz_core.c>`
`    Require all granted`
` `
`    <Files *.php>`
`        Require all denied`
`    </Files>`
` `
`    <Files ~*.txt>`
`        Require all denied`
`    </Files>`
` `
`    <files ".(xml|css|jpe?g|png|gif|js|ttf|wof|eof)$">`
`        Require all granted`
`    </files>`
`</IfModule>`

Please let us know if this resolves the issue for you.

**Comment by ferreto1978** [comment]
Setting the apache server to version 2.2, it kicked in after refreshing the page. First I got an error, but after re-entering the credentials, the sync worked.

When I set apache back to version 2.4 (after refreshing the page) the problem came back, so then I added the code you presented for apache 2.4 in the .htaccess file, and it did work again.

Hopefully the new version wil be available soon.
In the meantime, thank you very much for your support.
This will save me quite some time on syncing pages.

**Comment by davejesch** [comment]
Hi @ferreto1978,

Glad to hear that it's working for you. Please feel free to give us feedback as you start using it more.

The next release is just waiting some final testing on some new features added for some new add-ons that will also be released as soon as these are complete.
